spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: httpbin
          uri: http://httpbin.org:80
          predicates:
            - Path=/get
          filters:
            - AddRequestHeader=MyHeader,MyURI
            - AddRequestParameter=Param,Value

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/user/**
          filters:
            - name: Retry
              args:
                retries: 3
                methods: GET,POST
            - name: CircuitBreaker
              args:
                name: user-service
                fallbackUri: forward:/fallback

        - id: product-service
          uri: lb://product-service
          predicates:
             - Path=/api/v1/product/**,/api/v1/productReview/**,/api/v1/categories/**
          filters:
            - name: Retry
              args:
                retries: 3
                methods: GET,POST
            - name: CircuitBreaker
              args:
                name: product-service
                fallbackUri: forward:/fallback

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/v1/orders/**
          filters:
            - name: Retry
              args:
                retries: 3
                methods: GET,POST
            - name: CircuitBreaker
              args:
                name: order-service
                fallbackUri: forward:/fallback

        - id: user-address-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/Address/**
          filters:
            - name: Retry
              args:
                retries: 3
                methods: GET,POST
            - name: CircuitBreaker
              args:
                name: user-service
                fallbackUri: forward:/fallback

server:
  port: 8765

management:
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_BASE_URL:http://zipkin:9411}/api/v2/spans

eureka:
  client:
    serviceUrl:
      defaultZone: http://naming-server:8761/eureka
  instance:
    prefer-ip-address: true
    hostname: localhost

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        waitDurationInOpenState: 10000
        slowCallDurationThreshold: 2000
        permittedNumberOfCallsInHalfOpenState: 3
    instances:
      user-service:
        baseConfig: default
      product-service:
        baseConfig: default

  retry:
    configs:
      default:
        maxAttempts: 3
        waitDuration: 1000
        retryExceptions:
          - java.io.IOException
          - java.net.ConnectException
    instances:
      user-service:
        baseConfig: default
      product-service:
        baseConfig: default

logging:
  pattern:
    level: "%5p [${spring.application.name}, %X{traceId:-}, %X{spanId:-}]"